// <auto-generated />
using System;
using BackendApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BackendApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.8");

            modelBuilder.Entity("BackendApi.Models.StudentQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AssignedPersona")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ConcreteExamplesScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("EthicsScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("JobFearScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KnowledgeScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OpportunityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("StudentName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("UtilityScore")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("StudentQuizzes");
                });
#pragma warning restore 612, 618
        }
    }
}
